### ISSUE TITLE
Unexpected Packet

### ISSUE THREAD

**Issue by glademiller** [blackbeam/rust-mysql-simple#160]
Azure MySQL running 5.7.21 connecting over SSH tunnel error Crate version 14.1.1
DriverError { Unexpected packet }

SSL is enabled with a CA Cert Key. 
Verify Peer is set to false.

I'm not sure if it is relevant but in my Go project I have to set 
tls=skip-verify&allowNativePasswords=true

**Comment by blackbeam** [comment]
Hi.
Could you please reveal your connection string or a part of code where your `Opts`/`OptsBuilder` is defined? **Make sure that your host/password is replaced with some dummy values!**

**Comment by blackbeam** [comment]
Backtrace will also be quite helpful. You can get one by running your app with `RUST_BACKTRACE=1` environment variable.

**Comment by blackbeam** [comment]
Btw, is it on windows or on linux host?

**Comment by blackbeam** [comment]
I've just tested it against 5.7.24 with ssl without issues.
Looks like i need more data to reproduce this issue.

**Comment by glademiller** [comment]
Apologies for the delayed response and thanks for your quick feedback. I am running on Linux against a MySQL hosted on Windows in Azure. I build my connection options like so 

`    let mut builder = my::OptsBuilder::new();
    builder.db_name(Some("auth"));
    builder.ip_or_hostname(Some("localhost"));
    builder.pass(Some("NOTTHEPASSWORD"));
    builder.user(Some("NOTTHEUSER"));
    builder.tcp_port(3306);
    builder.verify_peer(false);
        builder.ssl_opts(Some((
            "/home/temp/Downloads/BaltimoreCyberTrustRoot.pem",
            None::<(String, String)>,
        )));
    let pool = my::Pool::new(builder);
let pool = pool.expect("Could not connect to database");` 

The last expect trigger the panic.

`thread 'main' panicked at 'Could not connect to database: DriverError { Unexpected packet }', src/libcore/result.rs:1009:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:211
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:476
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:390
   6: rust_begin_unwind
             at src/libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:77
   8: core::result::unwrap_failed
             at /rustc/6acbb5b65c06d82c867a94c54ce51dab4707ac61/src/libcore/macros.rs:26
   9: <core::result::Result<T, E>>::expect
             at /rustc/6acbb5b65c06d82c867a94c54ce51dab4707ac61/src/libcore/result.rs:835
  10: cct::main
             at src/main.rs:51
  11: std::rt::lang_start::{{closure}}
             at /rustc/6acbb5b65c06d82c867a94c54ce51dab4707ac61/src/libstd/rt.rs:74
  12: std::panicking::try::do_call
             at src/libstd/rt.rs:59
             at src/libstd/panicking.rs:310
  13: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:102
  14: std::rt::lang_start_internal
             at src/libstd/panicking.rs:289
             at src/libstd/panic.rs:398
             at src/libstd/rt.rs:58
  15: std::rt::lang_start
             at /rustc/6acbb5b65c06d82c867a94c54ce51dab4707ac61/src/libstd/rt.rs:74
  16: main
  17: __libc_start_main
  18: _start`

**Comment by glademiller** [comment]
@blackbeam What else can I provide to help debug this issue?

**Comment by blackbeam** [comment]
I'm on vacation until 12.8 without my laptop, so there is not much you can do, unfortunately.
However you can try to look into the content of unexpected packet (it is in`payload` [here][1]). This might help me to identify problem without duplicating your environment.

[1]: https://github.com/blackbeam/rust-mysql-simple/blob/master/src/conn/mod.rs#L934

**Comment by glademiller** [comment]
Enjoy your vacation I'll take a look and let you know what I find.

**Comment by glademiller** [comment]
The first part of the packet is this 
fe, 6d, 79, 73, 71, 6c, 5f, 6e, 61, 74, 69, 76, 65, 5f, 70, 61, 73, 73, 77, 6f, 72, 64, 0
which appears to correspond to 

If CLIENT_PLUGIN_AUTH was set and the server wants the client to authenticate with the Authentication::Native41 method it sends:

2c 00 00 02 fe 6d 79 73    71 6c 5f 6e 61 74 69 76    ,....mysql_nativ
65 5f 70 61 73 73 77 6f    72 64 00 7a 51 67 34 69    e_password.zQg4i
36 6f 4e 79 36 3d 72 48    4e 2f 3e 2d 62 29 41 00    6oNy6=rHN/>-b)A.

From here https://dev.mysql.com/doc/internals/en/connection-phase-packets.html

Seems like I might not be setting a flag correctly perhaps?

**Comment by glademiller** [comment]
Ok learning as I go it looks like we need support for Protocol::AuthSwitchRequest packets coming in it should respond with Protocol::AuthSwitchResponse

**Comment by glademiller** [comment]
Hacked in fix that allows me to connect by capturing AuthSwitchRequest. In order to handle this correctly we would want to look at which method the AuthSwitchRequest packet is asking for and use that. My code here is hard coded to do mysql_native_password.

Added here https://github.com/blackbeam/rust-mysql-simple/blob/master/src/conn/mod.rs#L927

```rust
let payload = if payload[0] == 0xfe {
    let new_payload: Vec<u8> = payload.iter().skip(23).take(20).cloned().collect();
    let scramble = self
        .opts
        .get_pass()
        .and_then(|pass| scramble_native(&*new_payload, pass.as_bytes()));
    self.write_packet(&scramble.unwrap());
    self.read_packet()?
} else {
    payload
};
