### ISSUE TITLE
How do I get Datetime-type data?

### ISSUE THREAD

**Issue by perfy576** [blackbeam/rust-mysql-simple#186]
`login_time` is datetime in mysql.

# 1
```rust
let login_time: ???? = row.take("login_time").unwrap();
```
Where ????  What type should I fill in?

# 2
```rust

    let result = pool.prep_exec(&sql, ()).unwrap();
    let query_date: Vec<Password> = result
        .map(|row| {
            let (userid, lock_time)= mysql::from_row(row.unwrap());
            let pwd = Password {
                userid: userid,
                lock_time: lock_time,
            };
            return pwd;
        })
        .collect();
```
When I run, I will report an error. 
```
thread 'actix-rt:worker:0' panicked at 'Couldn't convert Row { userid: Bytes("100000"), lock_time: Date("\'2019-09-07 18:12:16\'") } to type (T1, T2). (see FromRow documentation)', /root/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/mysql_common-0.18.0/src/row/convert.rs:179:39
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
How can I get this Datetime data?

**Comment by blackbeam** [comment]
Hi.

> Where ???? What type should I fill in?

For the list of supported types and some details please see [the table on the main page of the `mysql_common` crate docs](https://docs.rs/mysql_common/0.18.0/mysql_common/).

> When I run, I will report an error.

To say something here i'll need the `Password` struct definition.

**Comment by perfy576** [comment]
> Hi.
> 
> > Where ???? What type should I fill in?
> 
> For the list of supported types and some details please see [the table on the main page of the `mysql_common` crate docs](https://docs.rs/mysql_common/0.18.0/mysql_common/).
> 
> > When I run, I will report an error.
> 
> To say something here i'll need the `Password` struct definition.

```rust
struct Password {
    userid: u64,
    lock_time: String,
}
```
But I don't think it has anything to do with the definition of structure.
Just, how do I unpack from the Date type

```
thread 'actix-rt:worker:0' panicked at 'Could not retrieve String from Value', src/libcore/option.rs:1036:5
```

**Comment by blackbeam** [comment]
As you can see in the table mentioned in my previous comment rust String representation is only defined for mysql `Bytes` value, provided that it's a valid UTF-8.
Options for you are:
* change the type of the `lock_time` field to something compatible (e.g. `chrono::NaiveDayeTime`)
* get lock_time as a raw `Value` and define your own string representation ([here is][1] the one used for ` Debug` impl).

[1]: https://github.com/blackbeam/rust_mysql_common/blob/master/src/value/mod.rs#L389

**Comment by blackbeam** [comment]
Hi.
Closing due to inactivity. Feel free to reopen.
